spring.application.name=robot-simulator

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

robot.simulator.kafka.topic=robot.telemetry
robot.simulator.kafka.lifecycle-topic=robot.lifecycle
robot.simulator.robot-count=3
robot.simulator.telemetry-interval-ms=1000
robot.simulator.state-advance-interval-ms=1000
robot.simulator.map-min-x=0
robot.simulator.map-max-x=100
robot.simulator.map-min-y=0
robot.simulator.map-max-y=100
