spring.application.name=robot-simulator

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=robot-simulator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.robofleet.robotsimulator.*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

robot.simulator.kafka.topic=robot.telemetry
robot.simulator.kafka.lifecycle-topic=robot.lifecycle
robot.simulator.robot-count=3
robot.simulator.telemetry-interval-ms=1000
robot.simulator.state-advance-interval-ms=1000
robot.simulator.map-min-x=0
robot.simulator.map-max-x=100
robot.simulator.map-min-y=0
robot.simulator.map-max-y=100
